# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger is the branch this pipeline will be pointing to
trigger:
- master

#Configured Build Server from Nick's VM. By default the Default points to empty server, so use Microsoft hosted Agents
pool:
  vmImage: 'windows-2019'

# - dev
# - staging

# 
# pool:
#   vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  pathtosolution: 'Pizzabox.client'
  pathtoproject: 'PizzaWebsite'
  pathtotest: 'Pizzabox.test'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
